/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author JuanMistery
 */
public class FrmPrincipalEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FrmPrincipalEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dspEmpleado = new javax.swing.JDesktopPane();
        mnbEmpleado = new javax.swing.JMenuBar();
        mnuRegistrar = new javax.swing.JMenu();
        mniReserva = new javax.swing.JMenuItem();
        mniPago = new javax.swing.JMenuItem();
        mniDevolucion = new javax.swing.JMenuItem();
        mnuGenerar = new javax.swing.JMenu();
        mniComprobante = new javax.swing.JMenuItem();
        mniHistorialConsumo = new javax.swing.JMenuItem();
        mniReporteIngresos = new javax.swing.JMenuItem();
        mnuLista = new javax.swing.JMenu();
        mniListaAutomoviles = new javax.swing.JMenuItem();
        mniListaGarajes = new javax.swing.JMenuItem();
        mniListaReservas = new javax.swing.JMenuItem();
        mniListaPagos = new javax.swing.JMenuItem();
        mnuOpciones = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleado de Agencia");

        javax.swing.GroupLayout dspEmpleadoLayout = new javax.swing.GroupLayout(dspEmpleado);
        dspEmpleado.setLayout(dspEmpleadoLayout);
        dspEmpleadoLayout.setHorizontalGroup(
            dspEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        dspEmpleadoLayout.setVerticalGroup(
            dspEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        mnuRegistrar.setText("Registrar");

        mniReserva.setText("Reserva");
        mnuRegistrar.add(mniReserva);

        mniPago.setText("Pago");
        mnuRegistrar.add(mniPago);

        mniDevolucion.setText("Devolucion");
        mnuRegistrar.add(mniDevolucion);

        mnbEmpleado.add(mnuRegistrar);

        mnuGenerar.setText("Generar");

        mniComprobante.setText("Comprobante");
        mnuGenerar.add(mniComprobante);

        mniHistorialConsumo.setText("Historial de Consumo");
        mnuGenerar.add(mniHistorialConsumo);

        mniReporteIngresos.setText("Reporte de Ingresos");
        mnuGenerar.add(mniReporteIngresos);

        mnbEmpleado.add(mnuGenerar);

        mnuLista.setText("Lista");

        mniListaAutomoviles.setText("Automoviles");
        mnuLista.add(mniListaAutomoviles);

        mniListaGarajes.setText("Garajes");
        mnuLista.add(mniListaGarajes);

        mniListaReservas.setText("Reservas");
        mnuLista.add(mniListaReservas);

        mniListaPagos.setText("Pagos");
        mnuLista.add(mniListaPagos);

        mnbEmpleado.add(mnuLista);

        mnuOpciones.setText("Opciones");
        mnbEmpleado.add(mnuOpciones);

        setJMenuBar(mnbEmpleado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dspEmpleado)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dspEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipalEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dspEmpleado;
    private javax.swing.JMenuBar mnbEmpleado;
    private javax.swing.JMenuItem mniComprobante;
    private javax.swing.JMenuItem mniDevolucion;
    private javax.swing.JMenuItem mniHistorialConsumo;
    private javax.swing.JMenuItem mniListaAutomoviles;
    private javax.swing.JMenuItem mniListaGarajes;
    private javax.swing.JMenuItem mniListaPagos;
    private javax.swing.JMenuItem mniListaReservas;
    private javax.swing.JMenuItem mniPago;
    private javax.swing.JMenuItem mniReporteIngresos;
    private javax.swing.JMenuItem mniReserva;
    private javax.swing.JMenu mnuGenerar;
    private javax.swing.JMenu mnuLista;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenu mnuRegistrar;
    // End of variables declaration//GEN-END:variables
}
