/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author JuanMistery
 */
public class FrmPrincipalAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipalAdministrador
     */
    public FrmPrincipalAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dspAdministrador = new javax.swing.JDesktopPane();
        mnbAdministrador = new javax.swing.JMenuBar();
        mnuCerrar = new javax.swing.JMenu();
        mnuAgregar = new javax.swing.JMenu();
        mniAgregarClientes = new javax.swing.JMenuItem();
        mniAgregarAutomoviles = new javax.swing.JMenuItem();
        mniAgregarGarajes = new javax.swing.JMenuItem();
        mniAgregarEmpleados = new javax.swing.JMenuItem();
        mniAgregarAgencias = new javax.swing.JMenuItem();
        mnuModificar = new javax.swing.JMenu();
        mniModificarCliente = new javax.swing.JMenuItem();
        mniModificarAutomovil = new javax.swing.JMenuItem();
        mniModificarGaraje = new javax.swing.JMenuItem();
        mniModificarAgencia = new javax.swing.JMenuItem();
        mnuListas = new javax.swing.JMenu();
        mniListaCliente = new javax.swing.JMenuItem();
        mniListaAutomóviles = new javax.swing.JMenuItem();
        mniListaGarajes = new javax.swing.JMenuItem();
        mniListaReserva = new javax.swing.JMenuItem();
        mniListaEmpleado = new javax.swing.JMenuItem();
        mniListaRegistro = new javax.swing.JMenuItem();
        mnuEliminar = new javax.swing.JMenu();
        mniEliminarCliente = new javax.swing.JMenuItem();
        mniEliminarAutomovil = new javax.swing.JMenuItem();
        mniEliminarGraaje = new javax.swing.JMenuItem();
        mniEliminarEmpleado = new javax.swing.JMenuItem();
        mniEliminarAgencia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dspAdministradorLayout = new javax.swing.GroupLayout(dspAdministrador);
        dspAdministrador.setLayout(dspAdministradorLayout);
        dspAdministradorLayout.setHorizontalGroup(
            dspAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        dspAdministradorLayout.setVerticalGroup(
            dspAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        mnuCerrar.setText("Cerrar");
        mnbAdministrador.add(mnuCerrar);

        mnuAgregar.setText("Agregar");

        mniAgregarClientes.setText("Clientes");
        mnuAgregar.add(mniAgregarClientes);

        mniAgregarAutomoviles.setText("Automóviles");
        mnuAgregar.add(mniAgregarAutomoviles);

        mniAgregarGarajes.setText("Garajes");
        mnuAgregar.add(mniAgregarGarajes);

        mniAgregarEmpleados.setText("Empleados");
        mniAgregarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarEmpleadosActionPerformed(evt);
            }
        });
        mnuAgregar.add(mniAgregarEmpleados);

        mniAgregarAgencias.setText("Agencias");
        mnuAgregar.add(mniAgregarAgencias);

        mnbAdministrador.add(mnuAgregar);

        mnuModificar.setText("Modificar");

        mniModificarCliente.setText("Cliente");
        mnuModificar.add(mniModificarCliente);

        mniModificarAutomovil.setText("Automóvil");
        mnuModificar.add(mniModificarAutomovil);

        mniModificarGaraje.setText("Garaje");
        mnuModificar.add(mniModificarGaraje);

        mniModificarAgencia.setText("Agencia");
        mnuModificar.add(mniModificarAgencia);

        mnbAdministrador.add(mnuModificar);

        mnuListas.setText("Listas");

        mniListaCliente.setText("Cliente");
        mnuListas.add(mniListaCliente);

        mniListaAutomóviles.setText("Automóviles");
        mnuListas.add(mniListaAutomóviles);

        mniListaGarajes.setText("Garajes");
        mnuListas.add(mniListaGarajes);

        mniListaReserva.setText("Reservas");
        mnuListas.add(mniListaReserva);

        mniListaEmpleado.setText("Empleados");
        mnuListas.add(mniListaEmpleado);

        mniListaRegistro.setText("Registros");
        mnuListas.add(mniListaRegistro);

        mnbAdministrador.add(mnuListas);

        mnuEliminar.setText("Eliminar");

        mniEliminarCliente.setText("Cliente");
        mnuEliminar.add(mniEliminarCliente);

        mniEliminarAutomovil.setText("Automóvil");
        mnuEliminar.add(mniEliminarAutomovil);

        mniEliminarGraaje.setText("Garaje");
        mnuEliminar.add(mniEliminarGraaje);

        mniEliminarEmpleado.setText("Empleado");
        mnuEliminar.add(mniEliminarEmpleado);

        mniEliminarAgencia.setText("Agencia");
        mnuEliminar.add(mniEliminarAgencia);

        mnbAdministrador.add(mnuEliminar);

        setJMenuBar(mnbAdministrador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dspAdministrador)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dspAdministrador)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAgregarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniAgregarEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipalAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dspAdministrador;
    private javax.swing.JMenuBar mnbAdministrador;
    private javax.swing.JMenuItem mniAgregarAgencias;
    private javax.swing.JMenuItem mniAgregarAutomoviles;
    private javax.swing.JMenuItem mniAgregarClientes;
    private javax.swing.JMenuItem mniAgregarEmpleados;
    private javax.swing.JMenuItem mniAgregarGarajes;
    private javax.swing.JMenuItem mniEliminarAgencia;
    private javax.swing.JMenuItem mniEliminarAutomovil;
    private javax.swing.JMenuItem mniEliminarCliente;
    private javax.swing.JMenuItem mniEliminarEmpleado;
    private javax.swing.JMenuItem mniEliminarGraaje;
    private javax.swing.JMenuItem mniListaAutomóviles;
    private javax.swing.JMenuItem mniListaCliente;
    private javax.swing.JMenuItem mniListaEmpleado;
    private javax.swing.JMenuItem mniListaGarajes;
    private javax.swing.JMenuItem mniListaRegistro;
    private javax.swing.JMenuItem mniListaReserva;
    private javax.swing.JMenuItem mniModificarAgencia;
    private javax.swing.JMenuItem mniModificarAutomovil;
    private javax.swing.JMenuItem mniModificarCliente;
    private javax.swing.JMenuItem mniModificarGaraje;
    private javax.swing.JMenu mnuAgregar;
    private javax.swing.JMenu mnuCerrar;
    private javax.swing.JMenu mnuEliminar;
    private javax.swing.JMenu mnuListas;
    private javax.swing.JMenu mnuModificar;
    // End of variables declaration//GEN-END:variables
}
