/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author JuanMistery
 */
public class FrmPrincipalAdministrador extends javax.swing.JFrame {

    int empleadoID;
    /**
     * Creates new form FrmPrincipalAdministrador
     */
    public FrmPrincipalAdministrador(int ID) {
        this.empleadoID=ID;
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dspAdministrador = new javax.swing.JDesktopPane();
        mnbAdministrador = new javax.swing.JMenuBar();
        mnuAgregar = new javax.swing.JMenu();
        mniAgregarClientes = new javax.swing.JMenuItem();
        mniAgregarAutomoviles = new javax.swing.JMenuItem();
        mniAgregarGarajes = new javax.swing.JMenuItem();
        mniAgregarEmpleados = new javax.swing.JMenuItem();
        mniAgregarAgencias = new javax.swing.JMenuItem();
        mnuModificar = new javax.swing.JMenu();
        mniModificarCliente = new javax.swing.JMenuItem();
        mniModificarAutomovil = new javax.swing.JMenuItem();
        mniModificarGaraje = new javax.swing.JMenuItem();
        mniModificarAgencia = new javax.swing.JMenuItem();
        mnuListas = new javax.swing.JMenu();
        mniListaCliente = new javax.swing.JMenuItem();
        mniListaAutomóviles = new javax.swing.JMenuItem();
        mniListaGarajes = new javax.swing.JMenuItem();
        mniListaEmpleado = new javax.swing.JMenuItem();
        mniListaAdministrador = new javax.swing.JMenuItem();
        mniListaRegistro = new javax.swing.JMenuItem();
        mniListaAgencia = new javax.swing.JRadioButtonMenuItem();
        mnuEliminar = new javax.swing.JMenu();
        mniEliminarCliente = new javax.swing.JMenuItem();
        mniEliminarAutomovil = new javax.swing.JMenuItem();
        mniEliminarGraaje = new javax.swing.JMenuItem();
        mniEliminarEmpleado = new javax.swing.JMenuItem();
        mniEliminarAgencia = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenu();
        mniCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        javax.swing.GroupLayout dspAdministradorLayout = new javax.swing.GroupLayout(dspAdministrador);
        dspAdministrador.setLayout(dspAdministradorLayout);
        dspAdministradorLayout.setHorizontalGroup(
            dspAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        dspAdministradorLayout.setVerticalGroup(
            dspAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        mnuAgregar.setText("Agregar");

        mniAgregarClientes.setText("Clientes");
        mniAgregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarClientesActionPerformed(evt);
            }
        });
        mnuAgregar.add(mniAgregarClientes);

        mniAgregarAutomoviles.setText("Automóviles");
        mnuAgregar.add(mniAgregarAutomoviles);

        mniAgregarGarajes.setText("Garajes");
        mniAgregarGarajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarGarajesActionPerformed(evt);
            }
        });
        mnuAgregar.add(mniAgregarGarajes);

        mniAgregarEmpleados.setText("Empleados");
        mniAgregarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarEmpleadosActionPerformed(evt);
            }
        });
        mnuAgregar.add(mniAgregarEmpleados);

        mniAgregarAgencias.setText("Agencias");
        mniAgregarAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarAgenciasActionPerformed(evt);
            }
        });
        mnuAgregar.add(mniAgregarAgencias);

        mnbAdministrador.add(mnuAgregar);

        mnuModificar.setText("Modificar");

        mniModificarCliente.setText("Cliente");
        mniModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModificarClienteActionPerformed(evt);
            }
        });
        mnuModificar.add(mniModificarCliente);

        mniModificarAutomovil.setText("Automóvil");
        mnuModificar.add(mniModificarAutomovil);

        mniModificarGaraje.setText("Garaje");
        mniModificarGaraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModificarGarajeActionPerformed(evt);
            }
        });
        mnuModificar.add(mniModificarGaraje);

        mniModificarAgencia.setText("Agencia");
        mniModificarAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniModificarAgenciaActionPerformed(evt);
            }
        });
        mnuModificar.add(mniModificarAgencia);

        mnbAdministrador.add(mnuModificar);

        mnuListas.setText("Listas");

        mniListaCliente.setText("Cliente");
        mniListaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListaClienteActionPerformed(evt);
            }
        });
        mnuListas.add(mniListaCliente);

        mniListaAutomóviles.setText("Automóviles");
        mnuListas.add(mniListaAutomóviles);

        mniListaGarajes.setText("Garajes");
        mniListaGarajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListaGarajesActionPerformed(evt);
            }
        });
        mnuListas.add(mniListaGarajes);

        mniListaEmpleado.setText("Empleados");
        mniListaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListaEmpleadoActionPerformed(evt);
            }
        });
        mnuListas.add(mniListaEmpleado);

        mniListaAdministrador.setText("Administradores");
        mniListaAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListaAdministradorActionPerformed(evt);
            }
        });
        mnuListas.add(mniListaAdministrador);

        mniListaRegistro.setText("Registros");
        mniListaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListaRegistroActionPerformed(evt);
            }
        });
        mnuListas.add(mniListaRegistro);

        mniListaAgencia.setSelected(true);
        mniListaAgencia.setText("Agencias");
        mniListaAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListaAgenciaActionPerformed(evt);
            }
        });
        mnuListas.add(mniListaAgencia);

        mnbAdministrador.add(mnuListas);

        mnuEliminar.setText("Eliminar");

        mniEliminarCliente.setText("Cliente");
        mniEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEliminarClienteActionPerformed(evt);
            }
        });
        mnuEliminar.add(mniEliminarCliente);

        mniEliminarAutomovil.setText("Automóvil");
        mnuEliminar.add(mniEliminarAutomovil);

        mniEliminarGraaje.setText("Garaje");
        mniEliminarGraaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEliminarGraajeActionPerformed(evt);
            }
        });
        mnuEliminar.add(mniEliminarGraaje);

        mniEliminarEmpleado.setText("Empleado");
        mnuEliminar.add(mniEliminarEmpleado);

        mniEliminarAgencia.setText("Agencia");
        mniEliminarAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEliminarAgenciaActionPerformed(evt);
            }
        });
        mnuEliminar.add(mniEliminarAgencia);

        mnbAdministrador.add(mnuEliminar);

        mnuCerrarSesion.setText("Cerrar Sesion");

        mniCerrar.setText("Cerrar");
        mniCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCerrarActionPerformed(evt);
            }
        });
        mnuCerrarSesion.add(mniCerrar);

        mnbAdministrador.add(mnuCerrarSesion);

        setJMenuBar(mnbAdministrador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dspAdministrador)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dspAdministrador)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAgregarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarEmpleadosActionPerformed
        centrarInternalFrame(new IfrmAgregarEmpleado(empleadoID));
    }//GEN-LAST:event_mniAgregarEmpleadosActionPerformed

    private void mniAgregarAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarAgenciasActionPerformed
        centrarInternalFrame(new IfrmAgregarAgencia(empleadoID));
    }//GEN-LAST:event_mniAgregarAgenciasActionPerformed

    private void mniListaAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListaAgenciaActionPerformed
        centrarInternalFrame(new IfrmListaAgencia());
    }//GEN-LAST:event_mniListaAgenciaActionPerformed

    private void mniCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCerrarActionPerformed
        this.dispose();
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_mniCerrarActionPerformed

    private void mniEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEliminarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniEliminarClienteActionPerformed

    private void mniAgregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarClientesActionPerformed
        IfrmAgregarCliente ifrmAgregarCliente = null;
        try {
            ifrmAgregarCliente = new IfrmAgregarCliente(empleadoID);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        centrarInternalFrame(ifrmAgregarCliente);
    }//GEN-LAST:event_mniAgregarClientesActionPerformed

    private void mniListaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListaRegistroActionPerformed
        IfrmListaRegistro ifrmListaRegistro = new IfrmListaRegistro();
        centrarInternalFrame(ifrmListaRegistro);
    }//GEN-LAST:event_mniListaRegistroActionPerformed

    private void mniListaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListaEmpleadoActionPerformed
        IfrmListaEmpleado ifrmListaEmpleado = null;
        try {
            ifrmListaEmpleado = new IfrmListaEmpleado();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmPrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        centrarInternalFrame(ifrmListaEmpleado);
    }//GEN-LAST:event_mniListaEmpleadoActionPerformed

    private void mniListaAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListaAdministradorActionPerformed
        IfrmListaAdministrador ifrmListaAdministrador = null;
        try {
            ifrmListaAdministrador = new IfrmListaAdministrador();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmPrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        centrarInternalFrame(ifrmListaAdministrador);
    }//GEN-LAST:event_mniListaAdministradorActionPerformed

    private void mniModificarAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModificarAgenciaActionPerformed
        IfrmModificarAgencia ifrmModificarAgencia = new IfrmModificarAgencia(empleadoID);
        centrarInternalFrame(ifrmModificarAgencia);
    }//GEN-LAST:event_mniModificarAgenciaActionPerformed

    private void mniEliminarAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEliminarAgenciaActionPerformed
        IfrmEliminarAgencia ifrmEliminarAgencia = new IfrmEliminarAgencia(empleadoID);
        centrarInternalFrame(ifrmEliminarAgencia);
    }//GEN-LAST:event_mniEliminarAgenciaActionPerformed

    private void mniListaGarajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListaGarajesActionPerformed
        IfrmListaGaraje ifrmListaGaraje = new IfrmListaGaraje();
        centrarInternalFrame(ifrmListaGaraje);
    }//GEN-LAST:event_mniListaGarajesActionPerformed

    private void mniAgregarGarajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarGarajesActionPerformed
        IfrmAgregarGaraje ifrmAgregarGaraje = new IfrmAgregarGaraje(empleadoID);
        centrarInternalFrame(ifrmAgregarGaraje);
    }//GEN-LAST:event_mniAgregarGarajesActionPerformed

    private void mniModificarGarajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModificarGarajeActionPerformed
        IfrmModificarGaraje ifrmModificarGaraje= new IfrmModificarGaraje(empleadoID);
        centrarInternalFrame(ifrmModificarGaraje);
    }//GEN-LAST:event_mniModificarGarajeActionPerformed

    private void mniEliminarGraajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEliminarGraajeActionPerformed
        IfrmEliminarGaraje ifrmEliminarGaraje = new IfrmEliminarGaraje(empleadoID);
        centrarInternalFrame(ifrmEliminarGaraje);
    }//GEN-LAST:event_mniEliminarGraajeActionPerformed

    private void mniModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModificarClienteActionPerformed
        IfrmModificarCliente ifrmModificarCliente = new IfrmModificarCliente();
        centrarInternalFrame(ifrmModificarCliente);
    }//GEN-LAST:event_mniModificarClienteActionPerformed

    private void mniListaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListaClienteActionPerformed
        IfrmListaCliente ifrmListaCliente = new IfrmListaCliente();
        centrarInternalFrame(ifrmListaCliente);
    }//GEN-LAST:event_mniListaClienteActionPerformed

    private void centrarInternalFrame(JInternalFrame interna) {
        int x = dspAdministrador.getWidth()/2 - interna.getWidth()/2;
        int y = dspAdministrador.getHeight()/2 - interna.getHeight()/2;
        if(interna.isShowing())
            interna.setLocation(x, y);
        else {
            dspAdministrador.add(interna);
            interna.setLocation(x, y);
            interna.show();
        }        
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dspAdministrador;
    private javax.swing.JMenuBar mnbAdministrador;
    private javax.swing.JMenuItem mniAgregarAgencias;
    private javax.swing.JMenuItem mniAgregarAutomoviles;
    private javax.swing.JMenuItem mniAgregarClientes;
    private javax.swing.JMenuItem mniAgregarEmpleados;
    private javax.swing.JMenuItem mniAgregarGarajes;
    private javax.swing.JMenuItem mniCerrar;
    private javax.swing.JMenuItem mniEliminarAgencia;
    private javax.swing.JMenuItem mniEliminarAutomovil;
    private javax.swing.JMenuItem mniEliminarCliente;
    private javax.swing.JMenuItem mniEliminarEmpleado;
    private javax.swing.JMenuItem mniEliminarGraaje;
    private javax.swing.JMenuItem mniListaAdministrador;
    private javax.swing.JRadioButtonMenuItem mniListaAgencia;
    private javax.swing.JMenuItem mniListaAutomóviles;
    private javax.swing.JMenuItem mniListaCliente;
    private javax.swing.JMenuItem mniListaEmpleado;
    private javax.swing.JMenuItem mniListaGarajes;
    private javax.swing.JMenuItem mniListaRegistro;
    private javax.swing.JMenuItem mniModificarAgencia;
    private javax.swing.JMenuItem mniModificarAutomovil;
    private javax.swing.JMenuItem mniModificarCliente;
    private javax.swing.JMenuItem mniModificarGaraje;
    private javax.swing.JMenu mnuAgregar;
    private javax.swing.JMenu mnuCerrarSesion;
    private javax.swing.JMenu mnuEliminar;
    private javax.swing.JMenu mnuListas;
    private javax.swing.JMenu mnuModificar;
    // End of variables declaration//GEN-END:variables
}
