/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.sql.SQLException;
import logica.businessLogic.BLCliente;
import logica.businessLogic.BLRegistro;

/**
 *
 * @author LOQ
 */
public class IfrmAgregarCliente extends javax.swing.JInternalFrame {

    int empleadoID;
    /**
     * Creates new form IfrmAgregarCliente
     */
    public IfrmAgregarCliente(int ID) throws SQLException {
        empleadoID=ID;
        initComponents();
        BLCliente.cargarSponsorsEnComboBox(cmbSponsor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgSponsor = new javax.swing.ButtonGroup();
        panAgregarCliente = new javax.swing.JPanel();
        lblNombreCliente = new javax.swing.JLabel();
        lblApellidoCliente = new javax.swing.JLabel();
        lblDniCliente = new javax.swing.JLabel();
        lblSponsorCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoCliente = new javax.swing.JTextField();
        txtDniCliente = new javax.swing.JTextField();
        lblImagenCliente = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        lblTelefonoCliente = new javax.swing.JLabel();
        lblDireccionCliente = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        rbtActivar = new javax.swing.JRadioButton();
        rbtDesactivar = new javax.swing.JRadioButton();
        cmbSponsor = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agregar Cliente");

        panAgregarCliente.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreCliente.setText("NOMBRE:");

        lblApellidoCliente.setText("APELLIDO:");

        lblDniCliente.setText("DNI:");

        lblSponsorCliente.setText("SPONSOR (ID):");

        txtNombreCliente.setEnabled(false);

        txtApellidoCliente.setEnabled(false);

        txtDniCliente.setEnabled(false);

        lblImagenCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente-1.png"))); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.gif"))); // NOI18N
        btnGuardar.setMnemonic('A');
        btnGuardar.setText("Agregar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_file.gif"))); // NOI18N
        btnNuevo.setMnemonic('N');
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        lblTelefonoCliente.setText("TELÉFONO:");

        lblDireccionCliente.setText("DIRECCIÓN:");

        txtTelefonoCliente.setEnabled(false);

        txtDireccionCliente.setEnabled(false);

        btgSponsor.add(rbtActivar);
        rbtActivar.setText("Activar");
        rbtActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtActivarActionPerformed(evt);
            }
        });

        btgSponsor.add(rbtDesactivar);
        rbtDesactivar.setText("Desactivar");
        rbtDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDesactivarActionPerformed(evt);
            }
        });

        cmbSponsor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSponsor.setEnabled(false);

        javax.swing.GroupLayout panAgregarClienteLayout = new javax.swing.GroupLayout(panAgregarCliente);
        panAgregarCliente.setLayout(panAgregarClienteLayout);
        panAgregarClienteLayout.setHorizontalGroup(
            panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgregarClienteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAgregarClienteLayout.createSequentialGroup()
                        .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellidoCliente)
                            .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombreCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDniCliente)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtApellidoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtNombreCliente)
                            .addComponent(txtDniCliente)))
                    .addGroup(panAgregarClienteLayout.createSequentialGroup()
                        .addComponent(lblTelefonoCliente)
                        .addGap(25, 25, 25)
                        .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panAgregarClienteLayout.createSequentialGroup()
                        .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAgregarClienteLayout.createSequentialGroup()
                                .addComponent(lblSponsorCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(panAgregarClienteLayout.createSequentialGroup()
                                .addComponent(lblDireccionCliente)
                                .addGap(21, 21, 21)))
                        .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDireccionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(cmbSponsor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panAgregarClienteLayout.createSequentialGroup()
                        .addComponent(rbtActivar)
                        .addGap(27, 27, 27)
                        .addComponent(rbtDesactivar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAgregarClienteLayout.createSequentialGroup()
                        .addComponent(lblImagenCliente)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAgregarClienteLayout.createSequentialGroup()
                        .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        panAgregarClienteLayout.setVerticalGroup(
            panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgregarClienteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoCliente)
                    .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDniCliente)
                    .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefonoCliente)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionCliente)
                    .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtActivar)
                    .addComponent(rbtDesactivar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(panAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSponsorCliente)
                    .addComponent(cmbSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(panAgregarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panAgregarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panAgregarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre = txtNombreCliente.getText();
        String apellido = txtApellidoCliente.getText();
        String telefono = txtTelefonoCliente.getText();
        String dni = txtDniCliente.getText();
        String direccion = txtDireccionCliente.getText();
        int resultado = BLCliente.insertarCliente(dni, SOMEBITS, nombre, apellido, telefono, direccion);
        if(resultado == 0){
            BLRegistro.registrarActividad(empleadoID, "ADMINISTRADOR", "INSERT" , "CLIENTE", "Se creo con exito un nuevo Cliente");
        }
        activar(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        activar(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void rbtActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtActivarActionPerformed
        cmbSponsor.setEnabled(true);
    }//GEN-LAST:event_rbtActivarActionPerformed

    private void rbtDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDesactivarActionPerformed
        cmbSponsor.setEnabled(false);
        cmbSponsor.setSelectedIndex(0);
    }//GEN-LAST:event_rbtDesactivarActionPerformed

    private void activar(boolean estado){
        txtNombreCliente.setEnabled(estado);
        txtApellidoCliente.setEnabled(estado);
        txtTelefonoCliente.setEnabled(estado);
        txtDniCliente.setEnabled(estado);
        txtDireccionCliente.setEnabled(estado);
        txtNombreCliente.setText("");
        txtApellidoCliente.setText("");
        txtTelefonoCliente.setText("");
        txtDniCliente.setText("");
        txtDireccionCliente.setText("");
        if(estado==false){
            cmbSponsor.setEnabled(estado);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgSponsor;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbSponsor;
    private javax.swing.JLabel lblApellidoCliente;
    private javax.swing.JLabel lblDireccionCliente;
    private javax.swing.JLabel lblDniCliente;
    private javax.swing.JLabel lblImagenCliente;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblSponsorCliente;
    private javax.swing.JLabel lblTelefonoCliente;
    private javax.swing.JPanel panAgregarCliente;
    private javax.swing.JRadioButton rbtActivar;
    private javax.swing.JRadioButton rbtDesactivar;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
