/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author LOQ
 */
public class IfrmAgregarEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmAgregarEmpleados
     */
    public IfrmAgregarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panAgregarEmpleado = new javax.swing.JPanel();
        lblNombreEmpleado = new javax.swing.JLabel();
        lblApellidoEmpleado = new javax.swing.JLabel();
        lblDireccionEmpleado = new javax.swing.JLabel();
        lblTelefonoEmpleado = new javax.swing.JLabel();
        lblUsuarioEmpleado = new javax.swing.JLabel();
        lblContraseniaEmpleado = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtApellidoEmpleado = new javax.swing.JTextField();
        txtDireccionEmpleado = new javax.swing.JTextField();
        txtTelefonoEmpleado = new javax.swing.JTextField();
        txtUsuarioEmpleado = new javax.swing.JTextField();
        txtContraseniaEmpleado = new javax.swing.JTextField();
        lblImagenEmpleado = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        cmbTiposDeEmpleado = new javax.swing.JComboBox<>();
        lblTipoEmpleado = new javax.swing.JLabel();
        lblIdAgencia = new javax.swing.JLabel();
        txtIDAgencia = new javax.swing.JTextField();

        setTitle("Agregar Empleado");

        panAgregarEmpleado.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreEmpleado.setText("NOMBRE:");

        lblApellidoEmpleado.setText("APELLIDO:");

        lblDireccionEmpleado.setText("DIRECCIÓN:");

        lblTelefonoEmpleado.setText("TELÉFONO:");

        lblUsuarioEmpleado.setText("USUARIO:");

        lblContraseniaEmpleado.setText("CONTRASEÑA:");

        lblImagenEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleado-1.png"))); // NOI18N

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_file.gif"))); // NOI18N
        btnNuevo.setMnemonic('N');
        btnNuevo.setText("Nuevo");

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.gif"))); // NOI18N
        btnAgregar.setMnemonic('A');
        btnAgregar.setText("Agregar");

        cmbTiposDeEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrador", "Empleado De Agencia" }));

        lblTipoEmpleado.setText("TIPO: ");

        lblIdAgencia.setText("ID AGENCIA:");

        javax.swing.GroupLayout panAgregarEmpleadoLayout = new javax.swing.GroupLayout(panAgregarEmpleado);
        panAgregarEmpleado.setLayout(panAgregarEmpleadoLayout);
        panAgregarEmpleadoLayout.setHorizontalGroup(
            panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgregarEmpleadoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panAgregarEmpleadoLayout.createSequentialGroup()
                        .addComponent(lblIdAgencia)
                        .addGap(18, 18, 18)
                        .addComponent(txtIDAgencia))
                    .addGroup(panAgregarEmpleadoLayout.createSequentialGroup()
                        .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreEmpleado)
                            .addComponent(lblApellidoEmpleado))
                        .addGap(27, 27, 27)
                        .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreEmpleado)
                            .addComponent(txtApellidoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                    .addGroup(panAgregarEmpleadoLayout.createSequentialGroup()
                        .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccionEmpleado)
                            .addComponent(lblTelefonoEmpleado)
                            .addComponent(lblUsuarioEmpleado))
                        .addGap(18, 18, 18)
                        .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionEmpleado)
                            .addComponent(txtTelefonoEmpleado)
                            .addComponent(txtUsuarioEmpleado)))
                    .addGroup(panAgregarEmpleadoLayout.createSequentialGroup()
                        .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraseniaEmpleado)
                            .addComponent(lblTipoEmpleado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContraseniaEmpleado)
                            .addComponent(cmbTiposDeEmpleado, 0, 201, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAgregarEmpleadoLayout.createSequentialGroup()
                        .addComponent(lblImagenEmpleado)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAgregarEmpleadoLayout.createSequentialGroup()
                        .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        panAgregarEmpleadoLayout.setVerticalGroup(
            panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgregarEmpleadoLayout.createSequentialGroup()
                .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAgregarEmpleadoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreEmpleado)
                            .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidoEmpleado)
                            .addComponent(txtApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDireccionEmpleado)
                            .addComponent(txtDireccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panAgregarEmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImagenEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panAgregarEmpleadoLayout.createSequentialGroup()
                        .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefonoEmpleado)
                            .addComponent(txtTelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuarioEmpleado)
                            .addComponent(txtUsuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseniaEmpleado)
                    .addComponent(txtContraseniaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTiposDeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdAgencia)
                    .addComponent(txtIDAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panAgregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbTiposDeEmpleado;
    private javax.swing.JLabel lblApellidoEmpleado;
    private javax.swing.JLabel lblContraseniaEmpleado;
    private javax.swing.JLabel lblDireccionEmpleado;
    private javax.swing.JLabel lblIdAgencia;
    private javax.swing.JLabel lblImagenEmpleado;
    private javax.swing.JLabel lblNombreEmpleado;
    private javax.swing.JLabel lblTelefonoEmpleado;
    private javax.swing.JLabel lblTipoEmpleado;
    private javax.swing.JLabel lblUsuarioEmpleado;
    private javax.swing.JPanel panAgregarEmpleado;
    private javax.swing.JTextField txtApellidoEmpleado;
    private javax.swing.JTextField txtContraseniaEmpleado;
    private javax.swing.JTextField txtDireccionEmpleado;
    private javax.swing.JTextField txtIDAgencia;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtTelefonoEmpleado;
    private javax.swing.JTextField txtUsuarioEmpleado;
    // End of variables declaration//GEN-END:variables
}
