/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import logica.businessLogic.BLAgencia;
import logica.businessLogic.BLRegistro;

/**
 *
 * @author JuanMistery
 */
public class IfrmModificarAgencia extends javax.swing.JInternalFrame {

    int empleadoID;
    /**
     * Creates new form IfrmRegistrarReserva
     */
    public IfrmModificarAgencia(int ID) {
        this.empleadoID=ID;
        initComponents();
        BLAgencia.cargarAgenciasEnComboBox(cmbAgencia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panModificarCliente = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNuevaDireccion = new javax.swing.JLabel();
        lblAgencia = new javax.swing.JLabel();
        cmbAgencia = new javax.swing.JComboBox<>();
        lblNuevoNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        txtDireccion = new javax.swing.JTextField();
        lblCambio = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Modificar Agencia");

        panModificarCliente.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblTitulo.setText("Modificar Agencia");

        lblNuevaDireccion.setText("Dirección:");

        lblAgencia.setText("Agencia:");

        cmbAgencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAgenciaActionPerformed(evt);
            }
        });

        lblNuevoNombre.setText("Nombre:");

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setMnemonic('G');
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblCambio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCambio.setText("Cambios:");

        javax.swing.GroupLayout panModificarClienteLayout = new javax.swing.GroupLayout(panModificarCliente);
        panModificarCliente.setLayout(panModificarClienteLayout);
        panModificarClienteLayout.setHorizontalGroup(
            panModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModificarClienteLayout.createSequentialGroup()
                .addGroup(panModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panModificarClienteLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panModificarClienteLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(panModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNuevoNombre)
                                    .addComponent(lblNuevaDireccion))
                                .addGap(35, 35, 35)
                                .addGroup(panModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTitulo)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(txtNombre)))
                            .addGroup(panModificarClienteLayout.createSequentialGroup()
                                .addComponent(lblAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCambio)))
                    .addGroup(panModificarClienteLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        panModificarClienteLayout.setVerticalGroup(
            panModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModificarClienteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addGap(42, 42, 42)
                .addGroup(panModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgencia)
                    .addComponent(cmbAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(lblCambio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevoNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panModificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevaDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panModificarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panModificarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int index = cmbAgencia.getSelectedIndex();
        String item = cmbAgencia.getItemAt(index);
        if(index!=0){
            int resultado= BLAgencia.actualizarAgencia(BLAgencia.obtenerAgencia(item).getIDAgencia(), txtNombre.getText(),txtDireccion.getText());
            if(resultado==0){
                BLRegistro.registrarActividad(empleadoID,"ADMINISTRADOR", "DELETE" , "AGENCIA", "Se elimino con exito una Agencia");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmbAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAgenciaActionPerformed
        int index = cmbAgencia.getSelectedIndex();
        String item = cmbAgencia.getItemAt(index);
        if (index == 0) {
        txtNombre.setText("");
        txtNombre.setEnabled(false);
        txtDireccion.setText("");
        txtDireccion.setEnabled(false);
        return; // Sale del método para evitar procesamiento adicional
        }
        if(BLAgencia.obtenerAgencia(index)!=null){
            txtNombre.setText(BLAgencia.obtenerAgencia(item).getNombreAgencia());
            txtNombre.setEnabled(true);
            txtDireccion.setText(BLAgencia.obtenerAgencia(item).getDireccionAgencia());
            txtDireccion.setEnabled(true);
        }
    }//GEN-LAST:event_cmbAgenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbAgencia;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblNuevaDireccion;
    private javax.swing.JLabel lblNuevoNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panModificarCliente;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
