/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import logica.businessLogic.BLAgencia;

/**
 *
 * @author LOQ
 */
public class IfrmAgregarAgencia extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmAgregarAgencia
     */
    public IfrmAgregarAgencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panAgregarAgencia = new javax.swing.JPanel();
        lblNombreAgencia = new javax.swing.JLabel();
        lblDireccionAgencia = new javax.swing.JLabel();
        txtNombreAgencia = new javax.swing.JTextField();
        txtDireccionAgencia = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setTitle("Agregar Agencia");

        panAgregarAgencia.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreAgencia.setText("NOMBRE:");

        lblDireccionAgencia.setText("DIRECCION:");

        txtNombreAgencia.setEnabled(false);

        txtDireccionAgencia.setEnabled(false);

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_file.gif"))); // NOI18N
        btnNuevo.setMnemonic('N');
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.gif"))); // NOI18N
        btnAgregar.setMnemonic('A');
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAgregarAgenciaLayout = new javax.swing.GroupLayout(panAgregarAgencia);
        panAgregarAgencia.setLayout(panAgregarAgenciaLayout);
        panAgregarAgenciaLayout.setHorizontalGroup(
            panAgregarAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgregarAgenciaLayout.createSequentialGroup()
                .addGroup(panAgregarAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAgregarAgenciaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panAgregarAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreAgencia)
                            .addComponent(lblDireccionAgencia))
                        .addGap(21, 21, 21)
                        .addGroup(panAgregarAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreAgencia)
                            .addComponent(txtDireccionAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                    .addGroup(panAgregarAgenciaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        panAgregarAgenciaLayout.setVerticalGroup(
            panAgregarAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgregarAgenciaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panAgregarAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAgencia)
                    .addComponent(txtNombreAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panAgregarAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionAgencia)
                    .addComponent(txtDireccionAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panAgregarAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panAgregarAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panAgregarAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        activar(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombreAgencia = txtNombreAgencia.getText();
        String DireccionAgencia = txtDireccionAgencia.getText();
        BLAgencia.insertarAgencia(nombreAgencia, DireccionAgencia);
        activar(false);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void activar(boolean estado){
        txtNombreAgencia.setEnabled(estado);
        txtNombreAgencia.setText("");
        txtDireccionAgencia.setEnabled(estado);
        txtDireccionAgencia.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel lblDireccionAgencia;
    private javax.swing.JLabel lblNombreAgencia;
    private javax.swing.JPanel panAgregarAgencia;
    private javax.swing.JTextField txtDireccionAgencia;
    private javax.swing.JTextField txtNombreAgencia;
    // End of variables declaration//GEN-END:variables
}
