/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.util.logging.Level;
import java.util.logging.Logger;
import logica.businessLogic.BLGaraje;
import logica.businessLogic.BLRegistro;

/**
 *
 * @author JuanMistery
 */
public class IfrmEliminarGaraje extends javax.swing.JInternalFrame {

    int empleadoID;
    /**
     * Creates new form IfrmRegistrarReserva
     */
    public IfrmEliminarGaraje(int ID) {
        this.empleadoID=ID;
        initComponents();
        BLGaraje.cargarAgenciasEnComboBox(cmbGaraje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panModificarGaraje = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNuevaDireccion = new javax.swing.JLabel();
        lblGaraje = new javax.swing.JLabel();
        cmbGaraje = new javax.swing.JComboBox<>();
        lblNuevoNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        txtDireccion = new javax.swing.JTextField();
        lblCambio = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Eliminar Garaje");

        panModificarGaraje.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblTitulo.setText("Eliminar Garaje");
        lblTitulo.setToolTipText("");

        lblNuevaDireccion.setText("Dirección:");

        lblGaraje.setText("Garaje:");

        cmbGaraje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGaraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGarajeActionPerformed(evt);
            }
        });

        lblNuevoNombre.setText("Nombre:");

        txtNombre.setEnabled(false);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setMnemonic('G');
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtDireccion.setEnabled(false);

        lblCambio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCambio.setText("Datos");

        javax.swing.GroupLayout panModificarGarajeLayout = new javax.swing.GroupLayout(panModificarGaraje);
        panModificarGaraje.setLayout(panModificarGarajeLayout);
        panModificarGarajeLayout.setHorizontalGroup(
            panModificarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModificarGarajeLayout.createSequentialGroup()
                .addGroup(panModificarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panModificarGarajeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panModificarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panModificarGarajeLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(panModificarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNuevoNombre)
                                    .addComponent(lblNuevaDireccion))
                                .addGap(35, 35, 35)
                                .addGroup(panModificarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTitulo)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(txtNombre)))
                            .addGroup(panModificarGarajeLayout.createSequentialGroup()
                                .addComponent(lblGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCambio)))
                    .addGroup(panModificarGarajeLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        panModificarGarajeLayout.setVerticalGroup(
            panModificarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModificarGarajeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addGap(42, 42, 42)
                .addGroup(panModificarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGaraje)
                    .addComponent(cmbGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCambio)
                .addGap(14, 14, 14)
                .addGroup(panModificarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevoNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panModificarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevaDireccion))
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panModificarGaraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panModificarGaraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGarajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGarajeActionPerformed
        int index = cmbGaraje.getSelectedIndex();
        String item = cmbGaraje.getItemAt(index);
        if (index == 0) {
        txtNombre.setText("");
        txtDireccion.setText("");
        return;
        }
        if(BLGaraje.obtenerGaraje(item)!=null){
            txtNombre.setText(BLGaraje.obtenerGaraje(item).getNombre());
            txtDireccion.setText(BLGaraje.obtenerGaraje(item).getDireccion());
        }
    }//GEN-LAST:event_cmbGarajeActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int index = cmbGaraje.getSelectedIndex();
        String item = cmbGaraje.getItemAt(index);
        if(index!=0){
            try {
                String mensaje = BLGaraje.eliminarGaraje(BLGaraje.obtenerGaraje(item).getGarajeID());
                if(mensaje==null){
                    BLRegistro.registrarActividad(empleadoID,"ADMINISTRADOR", "DELETE" , "GARAJE", "Se elimino con exito una Garaje");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(IfrmEliminarGaraje.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbGaraje;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblGaraje;
    private javax.swing.JLabel lblNuevaDireccion;
    private javax.swing.JLabel lblNuevoNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panModificarGaraje;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
