/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author LOQ
 */
public class IfrmEliminarGaraje extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmListaCliente
     */
    public IfrmEliminarGaraje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panEliminarGaraje = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaGarajes = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        btnElimlinar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Eliminar Garaje");

        panEliminarGaraje.setBackground(new java.awt.Color(255, 255, 255));

        tblListaGarajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Dirección"
            }
        ));
        jScrollPane1.setViewportView(tblListaGarajes);

        lblBuscar.setText("Buscar:");

        btnElimlinar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnElimlinar.setMnemonic('E');
        btnElimlinar.setText("Eliminar");

        javax.swing.GroupLayout panEliminarGarajeLayout = new javax.swing.GroupLayout(panEliminarGaraje);
        panEliminarGaraje.setLayout(panEliminarGarajeLayout);
        panEliminarGarajeLayout.setHorizontalGroup(
            panEliminarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEliminarGarajeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblBuscar)
                .addGap(30, 30, 30)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnElimlinar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(panEliminarGarajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );
        panEliminarGarajeLayout.setVerticalGroup(
            panEliminarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEliminarGarajeLayout.createSequentialGroup()
                .addGroup(panEliminarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEliminarGarajeLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panEliminarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBuscar)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panEliminarGarajeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnElimlinar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panEliminarGaraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panEliminarGaraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElimlinar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JPanel panEliminarGaraje;
    private javax.swing.JTable tblListaGarajes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
