/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author JuanMistery
 */
public class IfrmModificarAutomovil extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmRegistrarReserva
     */
    public IfrmModificarAutomovil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panModificarAutomovil = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNuevoGaraje = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        lblNuevaPlaca = new javax.swing.JLabel();
        txtNuevaPlaca = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        lblNuevoColor = new javax.swing.JLabel();
        txtNuevoColor = new javax.swing.JTextField();
        txtNuevoGaraje = new javax.swing.JTextField();
        lblCambios = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Modificar Automovil");

        panModificarAutomovil.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblTitulo.setText("Modificar Automóvil");

        lblNuevoGaraje.setText("Garaje Asignado: ");

        lblCliente.setText("Automóvil:");

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNuevaPlaca.setText("Placa:");

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setMnemonic('G');
        btnGuardar.setText("Guardar");

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo.setMnemonic('N');
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        lblNuevoColor.setText("Color:");

        txtNuevoGaraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoGarajeActionPerformed(evt);
            }
        });

        lblCambios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCambios.setText("Cambios:");

        javax.swing.GroupLayout panModificarAutomovilLayout = new javax.swing.GroupLayout(panModificarAutomovil);
        panModificarAutomovil.setLayout(panModificarAutomovilLayout);
        panModificarAutomovilLayout.setHorizontalGroup(
            panModificarAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModificarAutomovilLayout.createSequentialGroup()
                .addGroup(panModificarAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panModificarAutomovilLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panModificarAutomovilLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(panModificarAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panModificarAutomovilLayout.createSequentialGroup()
                                .addComponent(lblNuevoGaraje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNuevoGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panModificarAutomovilLayout.createSequentialGroup()
                                .addGroup(panModificarAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNuevaPlaca)
                                    .addComponent(lblNuevoColor))
                                .addGap(22, 22, 22)
                                .addGroup(panModificarAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNuevoColor, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNuevaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panModificarAutomovilLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panModificarAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCambios)
                            .addGroup(panModificarAutomovilLayout.createSequentialGroup()
                                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panModificarAutomovilLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblTitulo)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panModificarAutomovilLayout.setVerticalGroup(
            panModificarAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModificarAutomovilLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addGap(41, 41, 41)
                .addGroup(panModificarAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCambios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panModificarAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevaPlaca)
                    .addComponent(txtNuevaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panModificarAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevoColor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNuevoColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panModificarAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevoGaraje, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNuevoGaraje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panModificarAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panModificarAutomovil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panModificarAutomovil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtNuevoGarajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoGarajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoGarajeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JLabel lblCambios;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblNuevaPlaca;
    private javax.swing.JLabel lblNuevoColor;
    private javax.swing.JLabel lblNuevoGaraje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panModificarAutomovil;
    private javax.swing.JTextField txtNuevaPlaca;
    private javax.swing.JTextField txtNuevoColor;
    private javax.swing.JTextField txtNuevoGaraje;
    // End of variables declaration//GEN-END:variables
}
