/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author LOQ
 */
public class IfrmAgregarGaraje extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmAgregarGaraje
     */
    public IfrmAgregarGaraje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panAgregarGaraje = new javax.swing.JPanel();
        lblNombreGaraje = new javax.swing.JLabel();
        lblDireccionGaraje = new javax.swing.JLabel();
        txtNombreGaraje = new javax.swing.JTextField();
        txtDireccionGaraje = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Agregar Garaje");

        panAgregarGaraje.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreGaraje.setText("NOMBRE:");

        lblDireccionGaraje.setText("DIRECCIÓN:");

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo.setMnemonic('N');
        btnNuevo.setText("Nuevo");

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setMnemonic('A');
        btnAgregar.setText("Agregar");

        javax.swing.GroupLayout panAgregarGarajeLayout = new javax.swing.GroupLayout(panAgregarGaraje);
        panAgregarGaraje.setLayout(panAgregarGarajeLayout);
        panAgregarGarajeLayout.setHorizontalGroup(
            panAgregarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAgregarGarajeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panAgregarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreGaraje)
                    .addComponent(lblDireccionGaraje))
                .addGap(21, 21, 21)
                .addGroup(panAgregarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionGaraje))
                .addGap(112, 112, 112))
            .addGroup(panAgregarGarajeLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panAgregarGarajeLayout.setVerticalGroup(
            panAgregarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgregarGarajeLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panAgregarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreGaraje)
                    .addComponent(txtNombreGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panAgregarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionGaraje)
                    .addComponent(txtDireccionGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(panAgregarGarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnAgregar))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panAgregarGaraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panAgregarGaraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel lblDireccionGaraje;
    private javax.swing.JLabel lblNombreGaraje;
    private javax.swing.JPanel panAgregarGaraje;
    private javax.swing.JTextField txtDireccionGaraje;
    private javax.swing.JTextField txtNombreGaraje;
    // End of variables declaration//GEN-END:variables
}
